AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: index search Lambda
Resources:
  index-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos
      Description: 'index-photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-west-2:547958585700:function:index-photos'
      Environment:
        Variables:
          REGION: us-west-2
  search-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./search-photos
      Description: 'search-photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-west-2:547958585700:function:search-photos'
      Environment:
        Variables:
          REGION: us-west-2